[build]
  command = "pnpm run build"
  publish = "build"

[context.deploy-preview]
  command = "pnpm run build"
# This prevents the Netlify Dev plugin from overriding your build
# with a local server expectation