import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Fiskl help guide sidebar — aligned to the platform navigation structure.
 *
 * Atlas (Accountant Portal) has moved to its own docs instance at /atlas/*.
 * A cross-link at the bottom points users to the Atlas section.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',

    // ================================================================
    // ONBOARDING
    // ================================================================
    {
      type: 'category',
      label: '🚀 Getting Started',
      link: {type: 'doc', id: 'getting-started/overview'},
      collapsed: false,
      items: [
        'getting-started/as-a-business-owner',
        'getting-started/as-an-accountant',
        'getting-started/connecting-your-bank',
        'getting-started/importing-data',
        'getting-started/your-first-invoice',
        'getting-started/with-invoicing',
      ],
    },

    {
      type: 'category',
      label: 'Dashboard & Navigation',
      link: {type: 'doc', id: 'dashboard/overview'},
      items: [
        'dashboard/navigation-basics',
        'dashboard/customizing-dashboard',
      ],
    },

    {
      type: 'html',
      value: '<div class="sidebar-divider"></div>',
    },

    // ================================================================
    // SALES
    // ================================================================
    {
      type: 'html',
      value: '<div class="sidebar-section-label">Sales</div>',
    },

    {
      type: 'category',
      label: 'Invoicing & Quotes',
      link: {type: 'doc', id: 'invoicing/overview'},
      items: [
        'invoicing/creating-invoices',
        'invoicing/sending-invoices',
        'invoicing/invoice-management',
        'invoicing/creating-quotes',
        'invoicing/quote-management',
        'invoicing/create-recurring-invoices',
        'invoicing/recurring-invoice-management',
        'invoicing/invoice-payment-schedules',
      ],
    },

    {
      type: 'category',
      label: 'Clients',
      link: {type: 'doc', id: 'clients-vendors/overview'},
      items: [
        'clients-vendors/clients',
      ],
    },

    {
      type: 'html',
      value: '<div class="sidebar-divider"></div>',
    },

    // ================================================================
    // PURCHASES
    // ================================================================
    {
      type: 'html',
      value: '<div class="sidebar-section-label">Purchases</div>',
    },

    {
      type: 'category',
      label: 'Expenses',
      link: {type: 'doc', id: 'expenses/overview'},
      items: [
        'expenses/adding-expenses',
        {
          type: 'category',
          label: 'AI-Powered Expenses',
          link: {type: 'doc', id: 'expenses/ai-expenses/overview'},
          items: [
            'expenses/ai-expenses/uploading',
            'expenses/ai-expenses/managing-ai-expenses',
            'expenses/ai-expenses/reconciliation',
          ],
        },
        {
          type: 'category',
          label: 'Traditional Expenses',
          link: {type: 'doc', id: 'expenses/traditional-expenses/overview'},
          items: [{type: 'autogenerated', dirName: 'expenses/traditional-expenses'}],
        },
        'expenses/expense-categories',
      ],
    },

    {
      type: 'category',
      label: 'Time & Mileage',
      link: {type: 'doc', id: 'time-and-mileage/overview'},
      items: [
        'time-and-mileage/time-tracking',
        'time-and-mileage/mileage-tracking',
        'time-and-mileage/billing-time-and-mileage',
      ],
    },

    {
      type: 'category',
      label: 'Vendors',
      link: {type: 'doc', id: 'clients-vendors/overview'},
      items: [
        'clients-vendors/vendors',
      ],
    },

    {
      type: 'html',
      value: '<div class="sidebar-divider"></div>',
    },

    // ================================================================
    // ACCOUNTING
    // ================================================================
    {
      type: 'html',
      value: '<div class="sidebar-section-label">Accounting</div>',
    },

    {
      type: 'category',
      label: 'Accounting',
      link: {type: 'doc', id: 'accounting/overview'},
      items: [
        'accounting/chart-of-accounts',
        {
          type: 'category',
          label: 'Journal Entries',
          link: {type: 'doc', id: 'accounting/journal-entries/overview'},
          items: [
            {
              type: 'category',
              label: 'Transaction Guides',
              link: {type: 'doc', id: 'accounting/journal-entries/guides/overview'},
              items: [
                'accounting/journal-entries/guides/manual-transactions',
                'accounting/journal-entries/guides/match-and-split-transactions',
                'accounting/journal-entries/guides/move-transactions',
                'accounting/journal-entries/guides/accounts-receivable-transactions',
                'accounting/journal-entries/guides/accounts-payable-transactions',
                'accounting/journal-entries/guides/internal-transfers',
                'accounting/journal-entries/guides/multi-currency-transactions',
                'accounting/journal-entries/guides/opening-balances',
                'accounting/journal-entries/guides/exporting-transactions',
              ],
            },
            'accounting/journal-entries/multi-journal-entries',
          ],
        },
        {
          type: 'category',
          label: 'Reconciliation',
          link: {type: 'doc', id: 'accounting/reconciliation/overview'},
          items: [
            {
              type: 'category',
              label: 'Reconciliation Guides',
              link: {type: 'doc', id: 'accounting/reconciliation/guides/overview'},
              items: [
                'accounting/reconciliation/guides/how-fiskl-handles-reconciliation',
                'accounting/reconciliation/guides/bank-account-reconciliation',
                'accounting/reconciliation/guides/handling-reconciliation-discrepancies',
                'accounting/reconciliation/guides/reconciliation-best-practices',
                'accounting/reconciliation/guides/reconciliation-reports',
              ],
            },
          ],
        },
        'accounting/reimbursement-guide',
        'accounting/accounting-faqs',
      ],
    },

    {
      type: 'category',
      label: 'Financial Reports',
      link: {type: 'doc', id: 'reporting/overview'},
      items: [
        'reporting/profit-and-loss',
        'reporting/balance-sheet',
        'reporting/cash-flow',
        'reporting/expenses-report',
        'reporting/general-ledger',
        'reporting/trial-balance',
        'reporting/transactions-by-account',
        'reporting/statement-of-accounts',
        'reporting/client-aging',
        'reporting/sales-tax',
      ],
    },

    {
      type: 'html',
      value: '<div class="sidebar-divider"></div>',
    },

    // ================================================================
    // STANDALONE MAIN-NAV ITEMS
    // ================================================================

    {
      type: 'category',
      label: 'Products & Services',
      link: {type: 'doc', id: 'products-services/overview'},
      items: [
        'products-services/creating-products',
        'products-services/managing-services',
        'products-services/managing-catalog',
      ],
    },

    {
      type: 'category',
      label: 'Banking',
      link: {type: 'doc', id: 'integrations/banking/overview'},
      items: [
        'integrations/banking/connect-yodlee',
        'integrations/banking/connect-saltedge',
        'integrations/banking/connect-stripe',
        'integrations/banking/connect-wio',
      ],
    },

    {
      type: 'category',
      label: 'Team & Permissions',
      link: {type: 'doc', id: 'team/overview'},
      items: [
        'team/roles-permissions',
        'team/permissions-reference',
        'team/how-permissions-work',
        'team/inviting-users',
      ],
    },

    {
      type: 'category',
      label: 'Integrations & Automation',
      link: {type: 'doc', id: 'integrations/overview'},
      items: [
        {
          type: 'category',
          label: 'Payment Integrations',
          link: {type: 'doc', id: 'integrations/payments/overview'},
          items: [
            'integrations/payments/stripe-integration',
            'integrations/payments/gocardless-integration',
            'integrations/payments/paypal-integration',
          ],
        },
        {
          type: 'category',
          label: 'Public API',
          link: {type: 'doc', id: 'integrations/public-api/overview'},
          items: [
            'integrations/public-api/api-keys',
            'integrations/public-api/making-api-requests',
            'integrations/public-api/webhooks',
            'integrations/public-api/connected-apps',
          ],
        },
      ],
    },

    {
      type: 'html',
      value: '<div class="sidebar-divider"></div>',
    },

    // ================================================================
    // FI AI ADVISOR
    // ================================================================

    {
      type: 'category',
      label: 'Fi AI Advisor',
      link: {type: 'doc', id: 'ai/overview'},
      items: [
        'ai/fi',
      ],
    },

    {
      type: 'html',
      value: '<div class="sidebar-divider"></div>',
    },

    // ================================================================
    // CROSS-LINK TO ATLAS
    // Replaces the old inline Accountant Portal section.
    // ================================================================
    {
      type: 'html',
      value: '<a href="/atlas" class="sidebar-atlas-link">Fiskl Atlas (Accountant Portal) →</a>',
    },

    // ================================================================
    // ADMINISTRATION
    // ================================================================
    {
      type: 'html',
      value: '<div class="sidebar-section-label">Administration</div>',
    },

    {
      type: 'category',
      label: 'Settings',
      link: {type: 'doc', id: 'settings/overview'},
      items: [
        'settings/company-settings',
        'settings/profile-settings',
        'settings/accounting-settings',
        'settings/locked-period',
        'settings/currency-management',
        'settings/tax-settings',
        'settings/tax-management',
        'settings/invoice-quotes-settings',
        'settings/invoice-template-brands-settings',
        'settings/sender-domain',
        'settings/languages',
      ],
    },

    {
      type: 'category',
      label: 'Plans & Billing',
      link: {type: 'doc', id: 'plans-billing/overview'},
      items: [
        'plans-billing/selecting-plans',
        'plans-billing/managing-subscription',
        'plans-billing/updating-billing-info',
        'plans-billing/applying-offer-codes',
        'plans-billing/canceling-subscription',
        'plans-billing/deleting-account',
      ],
    },

    {
      type: 'html',
      value: '<div class="sidebar-divider"></div>',
    },

    // ================================================================
    // REFERENCE
    // ================================================================
    {
      type: 'html',
      value: '<div class="sidebar-section-label">Reference</div>',
    },

    {
      type: 'category',
      label: 'Glossary',
      link: {type: 'doc', id: 'glossary/overview'},
      items: [
        'glossary/accounting-fundamentals',
        'glossary/accounts-and-transactions',
        'glossary/assets-and-liabilities',
        'glossary/cash-and-banking',
        'glossary/financial-statements',
      ],
    },

    {
      type: 'category',
      label: 'Support',
      link: {type: 'doc', id: 'support/overview'},
      items: [{type: 'autogenerated', dirName: 'support'}],
    },
  ],
};

export default sidebars;