import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Improved sidebar structure for Fiskl documentation
 * Optimized for both human readability and AI consumption
 * Follows a progressive disclosure pattern: Setup → Daily Operations → Advanced Features → Administration
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',

    // ============================================================================
    // SECTION 1: ONBOARDING & SETUP
    // ============================================================================
    {
      type: 'category',
      label: '🚀 Getting Started',
      link: { type: 'doc', id: 'getting-started/overview' },
      collapsed: false, // Keep expanded for new users
      items: [
        'getting-started/as-a-business-owner',
        'getting-started/as-an-accountant',
        'getting-started/connecting-your-bank',
        'getting-started/importing-data',
        'getting-started/your-first-invoice',
        'getting-started/with-invoicing',
      ],
    },

    {
      type: 'category',
      label: 'Dashboard & Navigation',
      link: { type: 'doc', id: 'dashboard/overview' },
      items: [
        'dashboard/navigation-basics',
        'dashboard/quick-actions',
        'dashboard/customizing-dashboard',
      ],
    },

    {
      type: 'html',
      value: '<div style="margin: 1.5rem 0 1rem 0; padding-top: 1rem; border-top: 2px solid var(--ifm-color-emphasis-300);"></div>',
    },

    // ============================================================================
    // SECTION 2: CORE FINANCIAL OPERATIONS
    // ============================================================================
    {
      type: 'html',
      value: '<div style="margin: 0 0 0.75rem 0.5rem; font-size: 0.75rem; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px; color: var(--ifm-color-emphasis-600); opacity: 0.8;">Core Operations</div>',
    },

    {
      type: 'category',
      label: 'Invoicing & Quotes',
      link: { type: 'doc', id: 'invoicing/overview' },
      items: [
        'invoicing/creating-invoices',
        'invoicing/sending-invoices',
        'invoicing/invoice-management',
        'invoicing/creating-quotes',
        'invoicing/quote-management',
        'invoicing/create-recurring-invoices',
        'invoicing/recurring-invoice-management',
        'invoicing/manual-payment-methods',
      ],
    },

    {
      type: 'category',
      label: 'Expenses',
      link: { type: 'doc', id: 'expenses/overview' },
      items: [
        {
          type: 'category',
          label: 'AI-Powered Expenses',
          link: { type: 'doc', id: 'expenses/ai-expenses/overview' },
          items: [
            'expenses/ai-expenses/uploading',
            'expenses/ai-expenses/managing-ai-expenses',
            'expenses/ai-expenses/reconciliation',
          ],
        },
        {
          type: 'category',
          label: 'Traditional Expenses',
          link: { type: 'doc', id: 'expenses/traditional-expenses/overview' },
          items: [{type: 'autogenerated', dirName: 'expenses/traditional-expenses'}],
        },
        'expenses/expense-categories',
      ],
    },

    {
      type: 'category',
      label: 'Time & Mileage',
      link: { type: 'doc', id: 'time-and-mileage/overview' },
      items: [
        'time-and-mileage/time-tracking',
        'time-and-mileage/mileage-tracking',
        'time-and-mileage/billing-time-and-mileage',
      ],
    },

    {
      type: 'html',
      value: '<div style="margin: 1.5rem 0 1rem 0; padding-top: 1rem; border-top: 2px solid var(--ifm-color-emphasis-300);"></div>',
    },

    // ============================================================================
    // SECTION 3: ACCOUNTING & FINANCIAL MANAGEMENT
    // ============================================================================
    {
      type: 'html',
      value: '<div style="margin: 0 0 0.75rem 0.5rem; font-size: 0.75rem; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px; color: var(--ifm-color-emphasis-600); opacity: 0.8;">Accounting & Compliance</div>',
    },

    {
      type: 'category',
      label: 'Accounting',
      link: { type: 'doc', id: 'accounting/overview' },
      items: [
        'accounting/chart-of-accounts',
        {
          type: 'category',
          label: 'Journal Entries',
          link: { type: 'doc', id: 'accounting/journal-entries/overview' },
          items: [
            {
              type: 'category',
              label: 'Transaction Guides',
              link: { type: 'doc', id: 'accounting/journal-entries/guides/overview' },
              items: [
                'accounting/journal-entries/guides/manual-transactions',
                'accounting/journal-entries/guides/match-and-split-transactions',
                'accounting/journal-entries/guides/move-transactions',
                'accounting/journal-entries/guides/accounts-receivable-transactions',
                'accounting/journal-entries/guides/accounts-payable-transactions',
                'accounting/journal-entries/guides/internal-transfers',
                'accounting/journal-entries/guides/multi-currency-transactions',
                'accounting/journal-entries/guides/opening-balances',
                'accounting/journal-entries/guides/exporting-transactions',
              ],
            },
            'accounting/journal-entries/multi-journal-entries',
          ],
        },
        {
          type: 'category',
          label: 'Reconciliation',
          link: { type: 'doc', id: 'accounting/reconciliation/overview' },
          items: [
            {
              type: 'category',
              label: 'Reconciliation Guides',
              link: { type: 'doc', id: 'accounting/reconciliation/guides/overview' },
              items: [
                'accounting/reconciliation/guides/how-fiskl-handles-reconciliation',
                'accounting/reconciliation/guides/bank-account-reconciliation',
                'accounting/reconciliation/guides/handling-reconciliation-discrepancies',
                'accounting/reconciliation/guides/reconciliation-best-practices',
                'accounting/reconciliation/guides/reconciliation-reports',
              ],
            },
          ],
        },
        'accounting/reimbursement-guide',
        'accounting/accounting-faqs',
      ],
    },

    {
      type: 'category',
      label: 'Financial Reports',
      link: { type: 'doc', id: 'reporting/overview' },
      items: [
        'reporting/profit-and-loss',
        'reporting/balance-sheet',
        'reporting/cash-flow',
        'reporting/general-ledger',
        'reporting/trial-balance',
        'reporting/transactions-by-account',
        'reporting/statement-of-accounts',
        'reporting/client-aging',
        'reporting/sales-tax',
      ],
    },

    {
      type: 'html',
      value: '<div style="margin: 1.5rem 0 1rem 0; padding-top: 1rem; border-top: 2px solid var(--ifm-color-emphasis-300);"></div>',
    },

    // ============================================================================
    // SECTION 4: BUSINESS RESOURCES & DATA
    // ============================================================================
    {
      type: 'html',
      value: '<div style="margin: 0 0 0.75rem 0.5rem; font-size: 0.75rem; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px; color: var(--ifm-color-emphasis-600); opacity: 0.8;">Business Resources</div>',
    },

    {
      type: 'category',
      label: 'Clients & Vendors',
      link: { type: 'doc', id: 'clients-vendors/overview' },
      items: [
        'clients-vendors/clients',
        'clients-vendors/vendors',
      ],
    },

    {
      type: 'category',
      label: 'Products & Services',
      link: { type: 'doc', id: 'products-services/overview' },
      items: [
        'products-services/creating-products',
        'products-services/managing-services',
        'products-services/managing-catalog',
      ],
    },

    {
      type: 'category',
      label: 'Integrations',
      link: { type: 'doc', id: 'integrations/overview' },
      items: [
        {
          type: 'category',
          label: 'Banking Integrations',
          link: { type: 'doc', id: 'integrations/banking/overview' },
          items: [
            'integrations/banking/connect-yodlee',
            'integrations/banking/connect-saltedge',
            'integrations/banking/connect-stripe',
            'integrations/banking/connect-wio',
          ],
        },
        {
          type: 'category',
          label: 'Payment Integrations',
          link: { type: 'doc', id: 'integrations/payments/overview' },
          items: [
            'integrations/payments/stripe-integration',
            'integrations/payments/gocardless-integration',
            'integrations/payments/paypal-integration',
          ],
        },
      ],
    },

    {
      type: 'category',
      label: 'AI Features',
      link: { type: 'doc', id: 'ai/overview' },
      items: [
        'ai/fi',
      ],
    },

    {
      type: 'html',
      value: '<div style="margin: 2rem 0 1.5rem 0; padding: 1rem 0; border-top: 3px solid var(--ifm-color-primary-dark); border-bottom: 3px solid var(--ifm-color-primary-dark); background: var(--ifm-color-primary-lightest); opacity: 0.15;"></div>',
    },

    // ============================================================================
    // SECTION 5: ACCOUNTANT PORTAL (Premium/Professional Section)
    // ============================================================================
    {
      type: 'html',
      value: '<div style="margin: 0 0 0.75rem 0.5rem; font-size: 0.75rem; font-weight: 700; text-transform: uppercase; letter-spacing: 0.75px; color: var(--ifm-color-primary);">👔 Professional Tools</div>',
    },

    {
      type: 'category',
      label: 'Accountant Portal',
      className: 'sidebar-portal-category',
      link: { type: 'doc', id: 'accountant-portal/overview' },
      collapsed: true, // Keep collapsed by default since it's specialized
      items: [
        {
          type: 'category',
          label: 'Portal Setup',
          link: { type: 'doc', id: 'accountant-portal/getting-started/overview' },
          items: [
            'accountant-portal/getting-started/setting-up-your-practice',
            'accountant-portal/getting-started/team-structure',
            'accountant-portal/getting-started/configuring-branches',
          ],
        },
        {
          type: 'category',
          label: 'Client Management',
          link: { type: 'doc', id: 'accountant-portal/client-management/overview' },
          items: [
            'accountant-portal/client-management/inviting-clients',
            'accountant-portal/client-management/accepting-client-invitations',
            'accountant-portal/client-management/client-connections',
            'accountant-portal/client-management/client-access-levels',
          ],
        },
        {
          type: 'category',
          label: 'Billing Models',
          link: { type: 'doc', id: 'accountant-portal/billing-models/overview' },
          items: [
            'accountant-portal/billing-models/client-pays-model',
            'accountant-portal/billing-models/bill-us-model',
            'accountant-portal/billing-models/switching-billing-models',
          ],
        },
        {
          type: 'category',
          label: 'Team Collaboration',
          link: { type: 'doc', id: 'accountant-portal/team-collaboration/overview' },
          items: [
            'accountant-portal/team-collaboration/managing-team-members',
            'accountant-portal/team-collaboration/roles-permissions',
            'accountant-portal/team-collaboration/branch-management',
            'accountant-portal/team-collaboration/workflow-assignments',
          ],
        },
        {
          type: 'category',
          label: 'Reports & Analytics',
          link: { type: 'doc', id: 'accountant-portal/reporting-analytics/overview' },
          items: [
            'accountant-portal/reporting-analytics/practice-dashboard',
            'accountant-portal/reporting-analytics/client-portfolio-view',
            'accountant-portal/reporting-analytics/billing-reports',
            'accountant-portal/reporting-analytics/team-performance',
          ],
        },
        {
          type: 'category',
          label: 'Partner Program',
          link: { type: 'doc', id: 'accountant-portal/partner-program/overview' },
          items: [
            'accountant-portal/partner-program/becoming-a-partner',
            'accountant-portal/partner-program/partner-benefits',
            'accountant-portal/partner-program/partner-resources',
            'accountant-portal/partner-program/referral-tracking',
          ],
        },
      ],
    },

    {
      type: 'html',
      value: '<div style="margin: 2rem 0 1.5rem 0; padding-top: 1rem; border-top: 2px solid var(--ifm-color-emphasis-300);"></div>',
    },

    // ============================================================================
    // SECTION 6: ADMINISTRATION & SETTINGS
    // ============================================================================
    {
      type: 'html',
      value: '<div style="margin: 0 0 0.75rem 0.5rem; font-size: 0.75rem; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px; color: var(--ifm-color-emphasis-600); opacity: 0.8;">Administration</div>',
    },

    {
      type: 'category',
      label: 'Settings',
      link: { type: 'doc', id: 'settings/overview' },
      items: [
        'settings/profile-settings',
        'settings/company-settings',
        'settings/accounting-settings',
        'settings/invoice-quotes-settings',
        'settings/invoice-template-brands-settings',
        'settings/tax-settings',
        'settings/tax-management',
        'settings/currency-management',
        'settings/languages',
      ],
    },

    {
      type: 'category',
      label: 'Team Management',
      link: { type: 'doc', id: 'team/overview' },
      items: [
        'team/inviting-users',
        'team/roles-permissions',
      ],
    },

    {
      type: 'category',
      label: 'Plans & Billing',
      link: { type: 'doc', id: 'plans-billing/overview' },
      items: [
        'plans-billing/selecting-plans',
        'plans-billing/managing-subscription',
        'plans-billing/updating-billing-info',
        'plans-billing/applying-offer-codes',
        'plans-billing/canceling-subscription',
        'plans-billing/deleting-account',
      ],
    },

    {
      type: 'html',
      value: '<div style="margin: 1.5rem 0 1rem 0; padding-top: 1rem; border-top: 2px solid var(--ifm-color-emphasis-300);"></div>',
    },

    // ============================================================================
    // SECTION 7: REFERENCE & HELP
    // ============================================================================
    {
      type: 'html',
      value: '<div style="margin: 0 0 0.75rem 0.5rem; font-size: 0.75rem; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px; color: var(--ifm-color-emphasis-600); opacity: 0.8;">Reference</div>',
    },

    {
      type: 'category',
      label: 'Glossary',
      link: { type: 'doc', id: 'glossary/overview' },
      items: [
        'glossary/accounting-fundamentals',
        'glossary/accounts-and-transactions',
        'glossary/assets-and-liabilities',
        'glossary/cash-and-banking',
        'glossary/financial-statements',
      ],
    },

    {
      type: 'category',
      label: 'Support',
      link: { type: 'doc', id: 'support/overview' },
      items: [{type: 'autogenerated', dirName: 'support'}],
    },
  ],
};

export default sidebars;