/**
 * Video registry — the single source of truth for every help-site video.
 *
 * Pages reference a video by ID, never by URL:
 *
 *     <VideoEmbed id="api-connect-claude" />
 *
 * That indirection is the point. Moving the library to YouTube, or moving the
 * CDN, is an edit to this file alone — no markdown page changes. Add
 * `provider: 'youtube'` and `youtubeId` to switch a single video over.
 *
 * Entries are normally generated by `npm run add-video`, which produces the
 * poster, captions and transcript and prints the block to paste in here.
 */

export type VideoProvider = 'self' | 'youtube';

/** Groups the video hub renders as sections. Keep in sync with CATEGORY_LABELS. */
export type VideoCategory =
    | 'api'
    | 'getting-started'
    | 'invoicing'
    | 'accounting'
    | 'banking';

export const CATEGORY_LABELS: Record<VideoCategory, string> = {
    'api': 'API and integrations',
    'getting-started': 'Getting started',
    'invoicing': 'Invoicing',
    'accounting': 'Accounting',
    'banking': 'Banking',
};

export interface VideoMeta {
    /** Stable slug. Never change it once published — pages and anchors use it. */
    id: string;
    title: string;
    /** One or two sentences. Feeds the VideoObject schema and the hub card. */
    description: string;
    /** ISO 8601 duration, e.g. 'PT4M12S'. Required by Google for video results. */
    duration: string;
    /** 'YYYY-MM-DD'. Also required by Google. */
    uploadDate: string;
    /** Defaults to 'self'. Set 'youtube' to serve this one video from YouTube. */
    provider?: VideoProvider;
    /** Self-hosted: filename within VIDEO_BASE. */
    src?: string;
    /** YouTube: the 11-character video id. */
    youtubeId?: string;
    /** Filename within POSTER_BASE. Omit for a generated title card. */
    poster?: string;
    /** WebVTT captions filename within VIDEO_BASE. */
    captions?: string;
    category: VideoCategory;
    /** The doc page this video belongs on. The hub links here, not to a video page. */
    docPath: string;
    /**
     * Spoken content as plain text. This is what makes the video retrievable:
     * video is opaque to search and to Fi's RAG index, the transcript is not.
     */
    transcript?: string;
    /** Spoken language. Drives the "this video is in English" note on translated pages. */
    lang?: string;
}

/**
 * CDN origin. Always a domain you control, never a raw provider hostname like
 * *.s3.amazonaws.com or *.cloudfront.net — that way the storage provider can
 * change without touching a single page or registry entry.
 *
 * Backed by a private S3 bucket fronted by CloudFront, with videos.fiskl.com
 * as a Route 53 alias. CloudFront's always-free tier covers 1 TB/month of
 * delivery and S3-to-CloudFront transfer is free, so realistic help-centre
 * traffic costs about a cent a month in storage.
 *
 * Videos are deliberately NOT served from Netlify: Netlify meters bandwidth at
 * ~20 credits/GB, so video traffic would exhaust the plan's credits quickly.
 */
export const VIDEO_BASE = 'https://videos.fiskl.com/';
export const POSTER_BASE = 'https://videos.fiskl.com/posters/';

export const videos: VideoMeta[] = [
    // Wave 1. `npm run add-video` prints each block ready to paste.
    //
    // Produced by `npm run add-video`. The transcript is still the draft written
    // before recording — replace it with the real spoken words (whisper will
    // generate it automatically once installed).
    {
        id: 'api-connect-claude',
        title: 'Connect Claude to your Fiskl account',
        description: 'Authorise an AI assistant to read and update your Fiskl data.',
        duration: 'PT4M8S',
        uploadDate: '2026-08-31',
        src: 'api-connect-claude2.mp4',
        poster: 'api-connect-claude2.jpg',
        captions: 'api-connect-claude2.vtt',
        category: 'api',
        docPath: '/integrations/public-api/connect-ai-assistant',
        transcript:
            'In this video we connect Claude to your Fiskl account so you can ask questions about ' +
            'your business and create invoices in plain language. Start in your AI assistant and find ' +
            'the setting for adding a connector or MCP server. Enter the Fiskl server address, then ' +
            'sign in with your normal Fiskl account when the browser opens. Fiskl shows a consent ' +
            'screen listing the permissions the assistant is asking for, such as viewing your ' +
            'invoicing or managing your contacts. Clear the checkbox for anything you do not want to ' +
            'grant. We recommend approving only the view permissions on your first connection, trying ' +
            'a few questions, then reconnecting with write permissions once you are confident. Select ' +
            'Allow to finish. Back in the assistant, the Fiskl tools are now available. Remember that ' +
            'the assistant can never do more than you can yourself, and it can only do what you ' +
            'approved on the consent screen.',
    },
    {
      id: 'custom-email-domain',
      title: 'Add a custom domain to Fiskl',
      description: 'Add a custom domain to Fiskl',
      duration: 'PT2M8S',
      uploadDate: '2026-08-31',
      src: 'custom-email-domain.mp4',
      poster: 'custom-email-domain.jpg',
      captions: 'custom-email-domain.vtt',
      category: 'api',
      docPath: 'docs/settings/sender-domain.md',
      transcript: 'Okay, in this video we\'re going to go through the custom domain. So navigate to the settings and to send a domain. And this is where you would add your email that you would like us to use if you wanted to send from your domain. So in this case I\'m going to use this email and add this domain. So once you add this domain it will be pending verification and you will have to add these three CNAME records to your DNS. Once you\'ve added those we will automatically detect that they\'ve been added and then we can start sending invoices and quotes using the email that you added. So you can use the refresh status and here you can see we are now approved. So you will see your deliverability score at the top. This is something we monitor and we tell you how your deliveries to your customers are going. We will also monitor the health of your domain. So down the bottom you will receive any advisory notifications about your domain. So these could include SPF records and DMARC records which are very important for email delivery. If we detect any issues we will notify you on this page. If you want to remove your domain at any time you can just remove the domain using the delete icon. So one thing to note we verify the domain part not the email. So if you wanted to change the email and keep the domain you wouldn\'t have to re-add the DNS. But that\'s how you do it. Now this is not strictly necessary. We deliver emails and we put the reply to as your company email address. So it\'s not a requirement but if you would like your customers to be receiving invoices and quotes from your email address then this is the way to do it.'
    },{
      id: 'audit-log',
      title: 'Learn about the Audit Log',
      description: 'How to use the Audit Log in Fiskl',
      duration: 'PT1M47S',
      uploadDate: '2026-08-31',
      src: 'audit-log.mp4',
      poster: 'audit-log.jpg',
      captions: 'audit-log.vtt',
      category: 'api',
      docPath: 'settings/audit-log',
      transcript: 'Okay, today we\'re going to cover the Audit Log. So the Audit Log lives in the bottom left menu with your avatar and Audit Log has its own screen. This page shows you all of the transactions that have been changed in your accounting transactions or your company settings. There\'s also payments and payment gateways and payment instructions that are audited. So here you can see if we have a look at a single transaction, this transaction was changed. If we open it up, we can see that there were five changes to this transaction and each one will display exactly what was changed. You can also expand it further to see all the fields of that transaction. So we don\'t only record the accounting transactions, we also have email delivery audits. So this is very useful for investigating why an email hasn\'t reached its recipient or why you\'re not receiving emails. But if you expand the bounces, it will tell you exactly why. So this address doesn\'t exist and it will not be retried. Some bounces are permanently quarantined and if the issue has been resolved, you\'ll need to reach out to support and we can request the quarantine to be lifted. So then the Audit Log, you can also see on the accounting transactions. So this is an audit of what happened to that exact transaction. So if we go to the same transaction that we looked at earlier in the Audit Log, at this time we will see it on the accounting transaction screen. So we can see when it was created, who edited it and what was changed on this transaction right within the transaction. So very useful. So that covers the Audit Log.'
  },
];

export const byId = (id: string): VideoMeta | undefined =>
    videos.find((video) => video.id === id);

/** Videos grouped by category, in CATEGORY_LABELS order. Used by the hub. */
export const byCategory = (): Array<{category: VideoCategory; items: VideoMeta[]}> =>
    (Object.keys(CATEGORY_LABELS) as VideoCategory[])
        .map((category) => ({
            category,
            items: videos.filter((video) => video.category === category),
        }))
        .filter((group) => group.items.length > 0);

export const videoUrl = (video: VideoMeta): string =>
    video.src ? `${VIDEO_BASE}${video.src}` : '';

export const posterUrl = (video: VideoMeta): string | undefined =>
    video.poster ? `${POSTER_BASE}${video.poster}` : undefined;

export const captionsUrl = (video: VideoMeta): string | undefined =>
    video.captions ? `${VIDEO_BASE}${video.captions}` : undefined;

/** 'PT4M12S' → '4:12'. Falls back to the raw value if it does not parse. */
export const humanDuration = (iso: string): string => {
    const match = /^PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?$/.exec(iso);
    if (!match) return iso;
    const [, h, m, s] = match;
    const hours = Number(h ?? 0);
    const minutes = Number(m ?? 0);
    const seconds = Number(s ?? 0);
    const mm = hours > 0 ? String(minutes).padStart(2, '0') : String(minutes);
    return hours > 0
        ? `${hours}:${mm}:${String(seconds).padStart(2, '0')}`
        : `${mm}:${String(seconds).padStart(2, '0')}`;
};
