/**
 * Video registry — the single source of truth for every help-site video.
 *
 * Pages reference a video by ID, never by URL:
 *
 *     <VideoEmbed id="api-connect-claude" />
 *
 * That indirection is the point. Moving the library to YouTube, or moving the
 * CDN, is an edit to this file alone — no markdown page changes. Add
 * `provider: 'youtube'` and `youtubeId` to switch a single video over.
 *
 * Entries are normally generated by `npm run add-video`, which produces the
 * poster, captions and transcript and prints the block to paste in here.
 */

export type VideoProvider = 'self' | 'youtube';

/** Groups the video hub renders as sections. Keep in sync with CATEGORY_LABELS. */
export type VideoCategory =
    | 'api'
    | 'getting-started'
    | 'invoicing'
    | 'accounting'
    | 'banking';

export const CATEGORY_LABELS: Record<VideoCategory, string> = {
    'api': 'API and integrations',
    'getting-started': 'Getting started',
    'invoicing': 'Invoicing',
    'accounting': 'Accounting',
    'banking': 'Banking',
};

export interface VideoMeta {
    /** Stable slug. Never change it once published — pages and anchors use it. */
    id: string;
    title: string;
    /** One or two sentences. Feeds the VideoObject schema and the hub card. */
    description: string;
    /** ISO 8601 duration, e.g. 'PT4M12S'. Required by Google for video results. */
    duration: string;
    /** 'YYYY-MM-DD'. Also required by Google. */
    uploadDate: string;
    /** Defaults to 'self'. Set 'youtube' to serve this one video from YouTube. */
    provider?: VideoProvider;
    /** Self-hosted: filename within VIDEO_BASE. */
    src?: string;
    /** YouTube: the 11-character video id. */
    youtubeId?: string;
    /** Filename within POSTER_BASE. Omit for a generated title card. */
    poster?: string;
    /** WebVTT captions filename within VIDEO_BASE. */
    captions?: string;
    category: VideoCategory;
    /** The doc page this video belongs on. The hub links here, not to a video page. */
    docPath: string;
    /**
     * Spoken content as plain text. This is what makes the video retrievable:
     * video is opaque to search and to Fi's RAG index, the transcript is not.
     */
    transcript?: string;
    /** Spoken language. Drives the "this video is in English" note on translated pages. */
    lang?: string;
}

/**
 * CDN origin. Always a domain you control, never a raw provider hostname like
 * *.s3.amazonaws.com or *.cloudfront.net — that way the storage provider can
 * change without touching a single page or registry entry.
 *
 * Backed by a private S3 bucket fronted by CloudFront, with videos.fiskl.com
 * as a Route 53 alias. CloudFront's always-free tier covers 1 TB/month of
 * delivery and S3-to-CloudFront transfer is free, so realistic help-centre
 * traffic costs about a cent a month in storage.
 *
 * Videos are deliberately NOT served from Netlify: Netlify meters bandwidth at
 * ~20 credits/GB, so video traffic would exhaust the plan's credits quickly.
 */
export const VIDEO_BASE = 'https://videos.fiskl.com/';
export const POSTER_BASE = 'https://videos.fiskl.com/posters/';

export const videos: VideoMeta[] = [
    // Wave 1. `npm run add-video` prints each block ready to paste.
    //
    // Produced by `npm run add-video`. The transcript is still the draft written
    // before recording — replace it with the real spoken words (whisper will
    // generate it automatically once installed).
    {
        id: 'api-connect-claude',
        title: 'Connect Claude to your Fiskl account',
        description:
            'Authorise an AI assistant to read and update your Fiskl data, and choose which permissions to grant.',
        duration: 'PT4M8S',
        uploadDate: '2026-08-30',
        src: 'api-connect-claude.mp4',
        poster: 'api-connect-claude.jpg',
        category: 'api',
        docPath: '/integrations/public-api/connect-ai-assistant',
        transcript:
            'In this video we connect Claude to your Fiskl account so you can ask questions about ' +
            'your business and create invoices in plain language. Start in your AI assistant and find ' +
            'the setting for adding a connector or MCP server. Enter the Fiskl server address, then ' +
            'sign in with your normal Fiskl account when the browser opens. Fiskl shows a consent ' +
            'screen listing the permissions the assistant is asking for, such as viewing your ' +
            'invoicing or managing your contacts. Clear the checkbox for anything you do not want to ' +
            'grant. We recommend approving only the view permissions on your first connection, trying ' +
            'a few questions, then reconnecting with write permissions once you are confident. Select ' +
            'Allow to finish. Back in the assistant, the Fiskl tools are now available. Remember that ' +
            'the assistant can never do more than you can yourself, and it can only do what you ' +
            'approved on the consent screen.',
    },
];

export const byId = (id: string): VideoMeta | undefined =>
    videos.find((video) => video.id === id);

/** Videos grouped by category, in CATEGORY_LABELS order. Used by the hub. */
export const byCategory = (): Array<{category: VideoCategory; items: VideoMeta[]}> =>
    (Object.keys(CATEGORY_LABELS) as VideoCategory[])
        .map((category) => ({
            category,
            items: videos.filter((video) => video.category === category),
        }))
        .filter((group) => group.items.length > 0);

export const videoUrl = (video: VideoMeta): string =>
    video.src ? `${VIDEO_BASE}${video.src}` : '';

export const posterUrl = (video: VideoMeta): string | undefined =>
    video.poster ? `${POSTER_BASE}${video.poster}` : undefined;

export const captionsUrl = (video: VideoMeta): string | undefined =>
    video.captions ? `${VIDEO_BASE}${video.captions}` : undefined;

/** 'PT4M12S' → '4:12'. Falls back to the raw value if it does not parse. */
export const humanDuration = (iso: string): string => {
    const match = /^PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?$/.exec(iso);
    if (!match) return iso;
    const [, h, m, s] = match;
    const hours = Number(h ?? 0);
    const minutes = Number(m ?? 0);
    const seconds = Number(s ?? 0);
    const mm = hours > 0 ? String(minutes).padStart(2, '0') : String(minutes);
    return hours > 0
        ? `${hours}:${mm}:${String(seconds).padStart(2, '0')}`
        : `${mm}:${String(seconds).padStart(2, '0')}`;
};
